### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by iansoper** [bevesce/unicode-symbols-search#11]
I'm running El Capitan (10.11.6) and I'm getting this error in the debug console when running the workflow:

`[2016-10-08 21:54:31][ERROR: input.scriptfilter] Code 127: /bin/bash: /usr/local/bin/python3.4: No such file or directory`

Looks like I'm running Python 2.7.10

**Comment by bevesce** [comment]
Right now script requires Python 3, if you would like to make it compatible with Python 2 PR would be welcome

**Comment by padde** [comment]
Current version is python 3.6. How about using the symlink `/usr/local/bin/python3` instead, which homebrew will point to the latest `3.x` version?

**Comment by bevesce** [comment]
I redone workflow in a way that keeps code inside Alfred without additional files and it doesn't require additional python installation so problem is solved, I think.
