### ISSUE TITLE
makes alfred search freeze

### ISSUE THREAD

**Issue by chiehkuo** [bevesce/unicode-symbols-search#12]
I am running Sierra. This workflow can be very useful but it keeps making the alfred search bar freeze in the middle of a symbol search. I use many other workflows and this never happens. Is there a fix? Thanks!

**Comment by bevesce** [comment]
It freezes because there's a lot of symbols to search through. I don't know if there's anything to be done (except rewriting workflow in something faster than Python).

**Comment by bevesce** [comment]
I have updated how workflow works. I'm not sure but maybe it's faster now. If you could check it and let me know that would be great.
