### ISSUE TITLE
Add runtime dependencies and full installation instructions to README

### ISSUE THREAD

**Issue by padde** [bevesce/unicode-symbols-search#13]
Most importantly, show the steps to install Python 3 via Homebrew, else the extension will not work. For example:

```markdown
* Install Homebrew (http://brew.sh)
* Install Python 3 with `brew install python3`
* Download and open Alfred workflow from https://github.com/bevesce/unicode-symbols-search/raw/master/alfred/Unicode%20Symbols%20Search.alfredworkflow
```

Related to #11 - the Python version used in the script will not work any more with the current Python version delivered by Homebrew.

**Comment by bevesce** [comment]
Steps 1 and 2 are no longer needed. I'm not sure if it's necessary to explain step 3 but I added it to the readme.

**Comment by padde** [comment]
@bevesce thanks for considering my remarks. Now that I think of it, the problem is likely to be me running OS X 10.10, which only ships with Python 2...

**Comment by bevesce** [comment]
Workflow now runs with python 2 that Alfred uses by default.
