### ISSUE TITLE
How to add more symbols?

### ISSUE THREAD

**Issue by egriff38** [bevesce/unicode-symbols-search#15]
So I've got these lovely [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) installed on my system and am in need of a way to search for them. Descriptions are built into the fonts, but I'm not sure what script to use to add these glyphs to the search. I can see that all it takes is appending the file, but I'd rather not do that for every single one if I can help it

**Comment by bevesce** [comment]
Yes, you only need new symbols to [this file](https://github.com/bevesce/unicode-symbols-search/blob/master/unicode_symbols_search/symbols.txt) and then regenerate script for workflow using [this script](https://github.com/bevesce/unicode-symbols-search/blob/master/generate_code_for_alfred.py).

The format of symbols.txt file is simple:
```
 ★| black star
<space><symbol>|<space><description>
```

I know nothing about linked Nerd Fonts or reading font files generally, sorry.

**Comment by ryanoasis** [comment]
@xepher0coded You can currently search 2 ways:

### Script

* via [this script](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh)

![nf-test-fonts](https://cloud.githubusercontent.com/assets/8083459/25462376/8dde5ae6-2abc-11e7-973b-12f3a011d135.png)

### Website

* via the [NerdFonts.com website](http://nerdfonts.com/#cheat-sheet):

![c-ithxowsauvvtx jpg small](https://cloud.githubusercontent.com/assets/8083459/25462313/2f2da9de-2abc-11e7-9098-715cdcd6d080.jpeg)
