### ISSUE TITLE
Outdated symbols list (missing newer emoji)

### ISSUE THREAD

**Issue by bgentry** [bevesce/unicode-symbols-search#16]
Hi there, thanks for the great Alfred workflow.

I noticed that it does not support newer emoji (avocado, bacon, man/woman shrugging). Is there an easy way to update the list to include these?

Thanks!

**Comment by bevesce** [comment]
I updated the list with the emoji I know of, I hope nothing else is missing

**Comment by bgentry** [comment]
Awesome, looks good!

One thing I noticed is that the high number of skin tone variants makes it hard to find a specific human emoji. I wonder if it might be better to group these together as Apple's emoji menu does, i.e. default to the yellow one and have a shortcut or additional menu step to let you then pick tone if applicable.

But that's a separate issue and certainly not necessary. Thanks again :)
