### ISSUE TITLE
Add support for unicode modifier keys

### ISSUE THREAD

**Issue by nikivdev** [bevesce/unicode-symbols-search#17]
[These ones](https://wincent.com/wiki/Unicode_representations_of_modifier_keys).

Searching for control in the workflow returns nothing. :(

**Comment by bevesce** [comment]
All of those symbols are in the workflow under their proper unicode names. For example:

- ⌃: up arrowhead
- ⇧: upwards white arrow
- ⌘: place of interest
- ⏎: return symbol
- ⏏: eject symbol
- ⌽: apl functional symbol circle stile

**Comment by nikivdev** [comment]
Oh my bad. Thank you.
