### ISSUE TITLE
Add emojis added in 2017

### ISSUE THREAD

**Issue by nikivdev** [bevesce/unicode-symbols-search#18]
Like [Pie](https://emojipedia.org/pie/) emoji.

**Comment by bevesce** [comment]
Could you prepare pull request?

**Comment by nikivdev** [comment]
I am actually using [this workflow](https://github.com/jsumners/alfred-emoji) now for searching emojis as it is faster to search things than Symbols. Symbols has a small delay I found.

I still use Symbols for unicode symbols searches though.
