### ISSUE TITLE
"New" version doesn't produce results that are as useful

### ISSUE THREAD

**Issue by matthewwithanm** [bevesce/unicode-symbols-search#19]
I've been using a very very old version of this forever. A friend just asked me about it so I traced it back to the site and saw there were a bunch of new updates. After updating, however, "command" no longer pulled up `⌘` and "control" didn't pull up `⌃`. In general, the results seemed less useful with long and strange descriptions.

In the meantime, I downgraded to 8a2f9b39029d8d1eda88841fecb052a22fa035d6. Thanks for one of my most used workflows!

<img width="593" alt="screen shot 2018-02-21 at 4 53 57 pm" src="https://user-images.githubusercontent.com/126263/36514416-2ebeabc4-1729-11e8-974b-799e6eb807eb.png">

**Comment by bevesce** [comment]
I messed up descriptions of some symbols at some point. I've fixed them in the last few commits thanks.

**Comment by matthewwithanm** [comment]
Sweet! Can't wait to check it out!

**Comment by matthewwithanm** [comment]
yay! works again! thanks (:
