### ISSUE TITLE
Unable to paste "space" characters

### ISSUE THREAD

**Issue by larsenwork** [bevesce/unicode-symbols-search#20]
# Can't get this to work 

when pressing return nothing happens

<img width="50%" alt="screenshot" src="https://user-images.githubusercontent.com/3859425/46600283-f87e0800-cae9-11e8-8c9e-71e72f639fa3.png">

# E.g. this works just fine 

when pressing return the characters is pasted

<img width="50%" alt="screenshot" src="https://user-images.githubusercontent.com/3859425/46600333-219e9880-caea-11e8-9ff2-9536c0181b20.png">

# My machine

* macOS 10.14
* alfred 3.7
* 2017 MBP

**Comment by bevesce** [comment]
Fixed. Thanks!
