### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by fotonick** [bevesce/unicode-symbols-search#21]
Thank you for this wonderful Alfred plugin. I use it several times a day. Thank you also for posting the source code. However, I wasn't able to find a license posted, which leaves me uncertain what rights you intend to grant other Github users like myself, if any. Would it be possible to post an explicit license to spell out the terms under which you are sharing the source code?

Thanks!

https://choosealicense.com/no-permission/
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository

**Comment by fotonick** [comment]
@bevesce Have you had any time to consider how you'd like the USS code to be licensed?

**Comment by bevesce** [comment]
Ok...
