### ISSUE TITLE
Increase size of the symbols in the chooser?

### ISSUE THREAD

**Issue by Natedude** [bevesce/unicode-symbols-search#23]
I would love it if I was able to see the symbols larger, and if possible to also have the drop down go down lower to fit more of the larger symbols. (or maybe some kind of grid display?) 

Doable?

**Comment by Natedude** [comment]
It could also be cool to have a way of showing my most used symbols so I don't always have to search and scroll in the choose to find it.

**Comment by bevesce** [comment]
> I would love it if I was able to see the symbols larger, and if possible to also have the drop down go down lower to fit more of the larger symbols. (or maybe some kind of grid display?)
> 
> Doable?

I don't know. Have you seen an Alfred workflow that has something like this?
