### ISSUE TITLE
Packal version bug

### ISSUE THREAD

**Issue by magp** [bevesce/unicode-symbols-search#3]
Hi,

Thanks for the workflow!

For the version you have loaded to packal.org, line 45 of the symbolssearch.py is the following:

```
open('/Users/piotrwilczynski/Desktop/a.txt', 'w').write(raw_symbol.encode('utf-8'))
```

This breaks the workflow for _most_ people. :)

Your current commit on github works perfectly.

Best,

Michael

**Comment by bevesce** [comment]
yup, I fixed this in repo and forgot about packal...
