### ISSUE TITLE
html code, css code, unicode ...

### ISSUE THREAD

**Issue by Sheraff** [bevesce/unicode-symbols-search#5]
Would you consider allowing users to paste the HTML / CSS / UNICODE instead of the actual symbol, through the use of various modifier keys?

**Comment by bevesce** [comment]
when is it necessary to use escaped code instead of just symbol?

**Comment by Sheraff** [comment]
When writing code I'd say, it could be useful.

**Comment by bevesce** [comment]
I was thinking the same and previous version of this workflow could do that. 
But I've never used it so I removed it to so if anybody will notice.
So I'm curious if you really wanted to paste code or something and couldn't.

**Comment by Sheraff** [comment]
Well yeah, sometimes I just hardcode an arrow or whatever in HTML or CSS. I tend to use amp-what for that but your workflow looks like a good replacement.

**Comment by bevesce** [comment]
But why not put `<meta charset="utf-8" />` in `<head>` and use symbol itself? It's more readable in my opinion, but maybe I'm missing something.

**Comment by Sheraff** [comment]
idk, greater compatibility? rapid prototyping? if a site like amp-what exists, there must be uses for it, no?

**Comment by bevesce** [comment]
That doesn't sound as great feature request
