### ISSUE TITLE
Include the Unicode Value in the Item Results

### ISSUE THREAD

**Issue by alisneaky** [bevesce/unicode-symbols-search#9]
I would like to have the actual unicode value (\uXXXX) to be printed in the Description below the character in the results.

This way I have a reverse look up of Unicode value when I search for items. So if I want to know the unicode value of Trademark, i can search for Trade and get that in the result as well. Not needed to be copied into the clipboard, although a different keyword for that would also be good.

**Comment by bevesce** [comment]
It's done in new version
